// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module normalize_array_array_ap_fixed_16u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        data_V_data_4_V_dout,
        data_V_data_4_V_empty_n,
        data_V_data_4_V_read,
        data_V_data_5_V_dout,
        data_V_data_5_V_empty_n,
        data_V_data_5_V_read,
        data_V_data_6_V_dout,
        data_V_data_6_V_empty_n,
        data_V_data_6_V_read,
        data_V_data_7_V_dout,
        data_V_data_7_V_empty_n,
        data_V_data_7_V_read,
        data_V_data_8_V_dout,
        data_V_data_8_V_empty_n,
        data_V_data_8_V_read,
        data_V_data_9_V_dout,
        data_V_data_9_V_empty_n,
        data_V_data_9_V_read,
        data_V_data_10_V_dout,
        data_V_data_10_V_empty_n,
        data_V_data_10_V_read,
        data_V_data_11_V_dout,
        data_V_data_11_V_empty_n,
        data_V_data_11_V_read,
        data_V_data_12_V_dout,
        data_V_data_12_V_empty_n,
        data_V_data_12_V_read,
        data_V_data_13_V_dout,
        data_V_data_13_V_empty_n,
        data_V_data_13_V_read,
        data_V_data_14_V_dout,
        data_V_data_14_V_empty_n,
        data_V_data_14_V_read,
        data_V_data_15_V_dout,
        data_V_data_15_V_empty_n,
        data_V_data_15_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write,
        res_V_data_8_V_din,
        res_V_data_8_V_full_n,
        res_V_data_8_V_write,
        res_V_data_9_V_din,
        res_V_data_9_V_full_n,
        res_V_data_9_V_write,
        res_V_data_10_V_din,
        res_V_data_10_V_full_n,
        res_V_data_10_V_write,
        res_V_data_11_V_din,
        res_V_data_11_V_full_n,
        res_V_data_11_V_write,
        res_V_data_12_V_din,
        res_V_data_12_V_full_n,
        res_V_data_12_V_write,
        res_V_data_13_V_din,
        res_V_data_13_V_full_n,
        res_V_data_13_V_write,
        res_V_data_14_V_din,
        res_V_data_14_V_full_n,
        res_V_data_14_V_write,
        res_V_data_15_V_din,
        res_V_data_15_V_full_n,
        res_V_data_15_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [15:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [15:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [15:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
input  [15:0] data_V_data_4_V_dout;
input   data_V_data_4_V_empty_n;
output   data_V_data_4_V_read;
input  [15:0] data_V_data_5_V_dout;
input   data_V_data_5_V_empty_n;
output   data_V_data_5_V_read;
input  [15:0] data_V_data_6_V_dout;
input   data_V_data_6_V_empty_n;
output   data_V_data_6_V_read;
input  [15:0] data_V_data_7_V_dout;
input   data_V_data_7_V_empty_n;
output   data_V_data_7_V_read;
input  [15:0] data_V_data_8_V_dout;
input   data_V_data_8_V_empty_n;
output   data_V_data_8_V_read;
input  [15:0] data_V_data_9_V_dout;
input   data_V_data_9_V_empty_n;
output   data_V_data_9_V_read;
input  [15:0] data_V_data_10_V_dout;
input   data_V_data_10_V_empty_n;
output   data_V_data_10_V_read;
input  [15:0] data_V_data_11_V_dout;
input   data_V_data_11_V_empty_n;
output   data_V_data_11_V_read;
input  [15:0] data_V_data_12_V_dout;
input   data_V_data_12_V_empty_n;
output   data_V_data_12_V_read;
input  [15:0] data_V_data_13_V_dout;
input   data_V_data_13_V_empty_n;
output   data_V_data_13_V_read;
input  [15:0] data_V_data_14_V_dout;
input   data_V_data_14_V_empty_n;
output   data_V_data_14_V_read;
input  [15:0] data_V_data_15_V_dout;
input   data_V_data_15_V_empty_n;
output   data_V_data_15_V_read;
output  [15:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [15:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [15:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [15:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [15:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [15:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [15:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [15:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;
output  [15:0] res_V_data_8_V_din;
input   res_V_data_8_V_full_n;
output   res_V_data_8_V_write;
output  [15:0] res_V_data_9_V_din;
input   res_V_data_9_V_full_n;
output   res_V_data_9_V_write;
output  [15:0] res_V_data_10_V_din;
input   res_V_data_10_V_full_n;
output   res_V_data_10_V_write;
output  [15:0] res_V_data_11_V_din;
input   res_V_data_11_V_full_n;
output   res_V_data_11_V_write;
output  [15:0] res_V_data_12_V_din;
input   res_V_data_12_V_full_n;
output   res_V_data_12_V_write;
output  [15:0] res_V_data_13_V_din;
input   res_V_data_13_V_full_n;
output   res_V_data_13_V_write;
output  [15:0] res_V_data_14_V_din;
input   res_V_data_14_V_full_n;
output   res_V_data_14_V_write;
output  [15:0] res_V_data_15_V_din;
input   res_V_data_15_V_full_n;
output   res_V_data_15_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg data_V_data_4_V_read;
reg data_V_data_5_V_read;
reg data_V_data_6_V_read;
reg data_V_data_7_V_read;
reg data_V_data_8_V_read;
reg data_V_data_9_V_read;
reg data_V_data_10_V_read;
reg data_V_data_11_V_read;
reg data_V_data_12_V_read;
reg data_V_data_13_V_read;
reg data_V_data_14_V_read;
reg data_V_data_15_V_read;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;
reg res_V_data_8_V_write;
reg res_V_data_9_V_write;
reg res_V_data_10_V_write;
reg res_V_data_11_V_write;
reg res_V_data_12_V_write;
reg res_V_data_13_V_write;
reg res_V_data_14_V_write;
reg res_V_data_15_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_state3;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    data_V_data_4_V_blk_n;
reg    data_V_data_5_V_blk_n;
reg    data_V_data_6_V_blk_n;
reg    data_V_data_7_V_blk_n;
reg    data_V_data_8_V_blk_n;
reg    data_V_data_9_V_blk_n;
reg    data_V_data_10_V_blk_n;
reg    data_V_data_11_V_blk_n;
reg    data_V_data_12_V_blk_n;
reg    data_V_data_13_V_blk_n;
reg    data_V_data_14_V_blk_n;
reg    data_V_data_15_V_blk_n;
reg    res_V_data_0_V_blk_n;
wire    ap_CS_fsm_state5;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg    res_V_data_8_V_blk_n;
reg    res_V_data_9_V_blk_n;
reg    res_V_data_10_V_blk_n;
reg    res_V_data_11_V_blk_n;
reg    res_V_data_12_V_blk_n;
reg    res_V_data_13_V_blk_n;
reg    res_V_data_14_V_blk_n;
reg    res_V_data_15_V_blk_n;
wire   [7:0] i_fu_11765_p2;
reg   [7:0] i_reg_12158;
wire    ap_CS_fsm_state2;
reg   [15:0] tmp_data_V_0_reg_12163;
wire    io_acc_block_signal_op46;
reg   [15:0] tmp_data_V_1_reg_12168;
reg   [15:0] tmp_data_V_2_reg_12173;
reg   [15:0] tmp_data_V_3_reg_12178;
reg   [15:0] tmp_data_V_4_reg_12183;
reg   [15:0] tmp_data_V_5_reg_12188;
reg   [15:0] tmp_data_V_6_reg_12193;
reg   [15:0] tmp_data_V_7_reg_12198;
reg   [15:0] tmp_data_V_8_reg_12203;
reg   [15:0] tmp_data_V_9_reg_12208;
reg   [15:0] tmp_data_V_10_reg_12213;
reg   [15:0] tmp_data_V_11_reg_12218;
reg   [15:0] tmp_data_V_12_reg_12223;
reg   [15:0] tmp_data_V_1322_reg_12228;
reg   [15:0] tmp_data_V_14_reg_12233;
reg   [15:0] tmp_data_V_15_reg_12238;
reg   [15:0] trunc_ln_reg_12243;
wire    ap_CS_fsm_state4;
reg   [15:0] trunc_ln708_s_reg_12248;
reg   [15:0] trunc_ln708_124_reg_12253;
reg   [15:0] trunc_ln708_125_reg_12258;
reg   [15:0] trunc_ln708_126_reg_12263;
reg   [15:0] trunc_ln708_127_reg_12268;
reg   [15:0] trunc_ln708_128_reg_12273;
reg   [15:0] trunc_ln708_129_reg_12278;
reg   [15:0] trunc_ln708_130_reg_12283;
reg   [15:0] trunc_ln708_131_reg_12288;
reg   [15:0] trunc_ln708_132_reg_12293;
reg   [15:0] trunc_ln708_133_reg_12298;
reg   [15:0] trunc_ln708_134_reg_12303;
reg   [15:0] trunc_ln708_135_reg_12308;
reg   [15:0] trunc_ln708_136_reg_12313;
reg   [15:0] trunc_ln708_137_reg_12318;
reg   [7:0] i_0_reg_650;
reg    ap_block_state1;
wire    io_acc_block_signal_op130;
wire  signed [15:0] mul_ln1118_148_fu_664_p0;
wire  signed [15:0] mul_ln1118_142_fu_667_p0;
wire  signed [15:0] mul_ln1118_139_fu_671_p0;
wire  signed [15:0] mul_ln1118_136_fu_683_p0;
wire  signed [15:0] mul_ln1118_147_fu_716_p0;
wire  signed [15:0] mul_ln1118_143_fu_722_p0;
wire  signed [15:0] mul_ln1118_135_fu_725_p0;
wire  signed [15:0] mul_ln1118_fu_728_p0;
wire  signed [15:0] mul_ln1118_145_fu_751_p0;
wire  signed [15:0] mul_ln1118_141_fu_753_p0;
wire  signed [15:0] mul_ln1118_137_fu_768_p0;
wire  signed [15:0] mul_ln1118_140_fu_779_p0;
wire  signed [15:0] mul_ln1118_149_fu_783_p0;
wire  signed [15:0] mul_ln1118_138_fu_801_p0;
wire  signed [15:0] mul_ln1118_144_fu_806_p0;
wire  signed [15:0] mul_ln1118_146_fu_823_p0;
wire   [25:0] mul_ln1118_fu_728_p2;
wire   [25:0] mul_ln1118_135_fu_725_p2;
wire   [25:0] mul_ln1118_136_fu_683_p2;
wire   [25:0] mul_ln1118_137_fu_768_p2;
wire   [25:0] mul_ln1118_138_fu_801_p2;
wire   [25:0] mul_ln1118_139_fu_671_p2;
wire   [25:0] mul_ln1118_140_fu_779_p2;
wire   [25:0] mul_ln1118_141_fu_753_p2;
wire   [25:0] mul_ln1118_142_fu_667_p2;
wire   [25:0] mul_ln1118_143_fu_722_p2;
wire   [25:0] mul_ln1118_144_fu_806_p2;
wire   [25:0] mul_ln1118_145_fu_751_p2;
wire   [25:0] mul_ln1118_146_fu_823_p2;
wire   [25:0] mul_ln1118_147_fu_716_p2;
wire   [25:0] mul_ln1118_148_fu_664_p2;
wire   [25:0] mul_ln1118_149_fu_783_p2;
wire   [0:0] icmp_ln48_fu_11759_p2;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_0_reg_650 <= i_reg_12158;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_650 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_12158 <= i_fu_11765_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_0_reg_12163 <= data_V_data_0_V_dout;
        tmp_data_V_10_reg_12213 <= data_V_data_10_V_dout;
        tmp_data_V_11_reg_12218 <= data_V_data_11_V_dout;
        tmp_data_V_12_reg_12223 <= data_V_data_12_V_dout;
        tmp_data_V_1322_reg_12228 <= data_V_data_13_V_dout;
        tmp_data_V_14_reg_12233 <= data_V_data_14_V_dout;
        tmp_data_V_15_reg_12238 <= data_V_data_15_V_dout;
        tmp_data_V_1_reg_12168 <= data_V_data_1_V_dout;
        tmp_data_V_2_reg_12173 <= data_V_data_2_V_dout;
        tmp_data_V_3_reg_12178 <= data_V_data_3_V_dout;
        tmp_data_V_4_reg_12183 <= data_V_data_4_V_dout;
        tmp_data_V_5_reg_12188 <= data_V_data_5_V_dout;
        tmp_data_V_6_reg_12193 <= data_V_data_6_V_dout;
        tmp_data_V_7_reg_12198 <= data_V_data_7_V_dout;
        tmp_data_V_8_reg_12203 <= data_V_data_8_V_dout;
        tmp_data_V_9_reg_12208 <= data_V_data_9_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln708_124_reg_12253 <= {{mul_ln1118_136_fu_683_p2[25:10]}};
        trunc_ln708_125_reg_12258 <= {{mul_ln1118_137_fu_768_p2[25:10]}};
        trunc_ln708_126_reg_12263 <= {{mul_ln1118_138_fu_801_p2[25:10]}};
        trunc_ln708_127_reg_12268 <= {{mul_ln1118_139_fu_671_p2[25:10]}};
        trunc_ln708_128_reg_12273 <= {{mul_ln1118_140_fu_779_p2[25:10]}};
        trunc_ln708_129_reg_12278 <= {{mul_ln1118_141_fu_753_p2[25:10]}};
        trunc_ln708_130_reg_12283 <= {{mul_ln1118_142_fu_667_p2[25:10]}};
        trunc_ln708_131_reg_12288 <= {{mul_ln1118_143_fu_722_p2[25:10]}};
        trunc_ln708_132_reg_12293 <= {{mul_ln1118_144_fu_806_p2[25:10]}};
        trunc_ln708_133_reg_12298 <= {{mul_ln1118_145_fu_751_p2[25:10]}};
        trunc_ln708_134_reg_12303 <= {{mul_ln1118_146_fu_823_p2[25:10]}};
        trunc_ln708_135_reg_12308 <= {{mul_ln1118_147_fu_716_p2[25:10]}};
        trunc_ln708_136_reg_12313 <= {{mul_ln1118_148_fu_664_p2[25:10]}};
        trunc_ln708_137_reg_12318 <= {{mul_ln1118_149_fu_783_p2[25:10]}};
        trunc_ln708_s_reg_12248 <= {{mul_ln1118_135_fu_725_p2[25:10]}};
        trunc_ln_reg_12243 <= {{mul_ln1118_fu_728_p2[25:10]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_10_V_blk_n = data_V_data_10_V_empty_n;
    end else begin
        data_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_10_V_read = 1'b1;
    end else begin
        data_V_data_10_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_11_V_blk_n = data_V_data_11_V_empty_n;
    end else begin
        data_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_11_V_read = 1'b1;
    end else begin
        data_V_data_11_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_12_V_blk_n = data_V_data_12_V_empty_n;
    end else begin
        data_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_12_V_read = 1'b1;
    end else begin
        data_V_data_12_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_13_V_blk_n = data_V_data_13_V_empty_n;
    end else begin
        data_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_13_V_read = 1'b1;
    end else begin
        data_V_data_13_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_14_V_blk_n = data_V_data_14_V_empty_n;
    end else begin
        data_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_14_V_read = 1'b1;
    end else begin
        data_V_data_14_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_15_V_blk_n = data_V_data_15_V_empty_n;
    end else begin
        data_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_15_V_read = 1'b1;
    end else begin
        data_V_data_15_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n;
    end else begin
        data_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_4_V_read = 1'b1;
    end else begin
        data_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n;
    end else begin
        data_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_5_V_read = 1'b1;
    end else begin
        data_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n;
    end else begin
        data_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_6_V_read = 1'b1;
    end else begin
        data_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n;
    end else begin
        data_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_7_V_read = 1'b1;
    end else begin
        data_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_8_V_blk_n = data_V_data_8_V_empty_n;
    end else begin
        data_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_8_V_read = 1'b1;
    end else begin
        data_V_data_8_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        data_V_data_9_V_blk_n = data_V_data_9_V_empty_n;
    end else begin
        data_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_data_9_V_read = 1'b1;
    end else begin
        data_V_data_9_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_10_V_blk_n = res_V_data_10_V_full_n;
    end else begin
        res_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_10_V_write = 1'b1;
    end else begin
        res_V_data_10_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_11_V_blk_n = res_V_data_11_V_full_n;
    end else begin
        res_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_11_V_write = 1'b1;
    end else begin
        res_V_data_11_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_12_V_blk_n = res_V_data_12_V_full_n;
    end else begin
        res_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_12_V_write = 1'b1;
    end else begin
        res_V_data_12_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_13_V_blk_n = res_V_data_13_V_full_n;
    end else begin
        res_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_13_V_write = 1'b1;
    end else begin
        res_V_data_13_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_14_V_blk_n = res_V_data_14_V_full_n;
    end else begin
        res_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_14_V_write = 1'b1;
    end else begin
        res_V_data_14_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_15_V_blk_n = res_V_data_15_V_full_n;
    end else begin
        res_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_15_V_write = 1'b1;
    end else begin
        res_V_data_15_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n;
    end else begin
        res_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_8_V_write = 1'b1;
    end else begin
        res_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n;
    end else begin
        res_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_V_data_9_V_write = 1'b1;
    end else begin
        res_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln48_fu_11759_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((io_acc_block_signal_op46 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((io_acc_block_signal_op130 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign i_fu_11765_p2 = (i_0_reg_650 + 8'd1);

assign icmp_ln48_fu_11759_p2 = ((i_0_reg_650 == 8'd169) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op130 = (res_V_data_9_V_full_n & res_V_data_8_V_full_n & res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_15_V_full_n & res_V_data_14_V_full_n & res_V_data_13_V_full_n & res_V_data_12_V_full_n & res_V_data_11_V_full_n & res_V_data_10_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op46 = (data_V_data_9_V_empty_n & data_V_data_8_V_empty_n & data_V_data_7_V_empty_n & data_V_data_6_V_empty_n & data_V_data_5_V_empty_n & data_V_data_4_V_empty_n & data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_15_V_empty_n & data_V_data_14_V_empty_n & data_V_data_13_V_empty_n & data_V_data_12_V_empty_n & data_V_data_11_V_empty_n & data_V_data_10_V_empty_n & data_V_data_0_V_empty_n);

assign mul_ln1118_135_fu_725_p0 = tmp_data_V_1_reg_12168;

assign mul_ln1118_135_fu_725_p2 = ($signed(mul_ln1118_135_fu_725_p0) * $signed('h453));

assign mul_ln1118_136_fu_683_p0 = tmp_data_V_2_reg_12173;

assign mul_ln1118_136_fu_683_p2 = ($signed(mul_ln1118_136_fu_683_p0) * $signed('h385));

assign mul_ln1118_137_fu_768_p0 = tmp_data_V_3_reg_12178;

assign mul_ln1118_137_fu_768_p2 = ($signed(mul_ln1118_137_fu_768_p0) * $signed('h3B9));

assign mul_ln1118_138_fu_801_p0 = tmp_data_V_4_reg_12183;

assign mul_ln1118_138_fu_801_p2 = ($signed(mul_ln1118_138_fu_801_p0) * $signed('h332));

assign mul_ln1118_139_fu_671_p0 = tmp_data_V_5_reg_12188;

assign mul_ln1118_139_fu_671_p2 = ($signed(mul_ln1118_139_fu_671_p0) * $signed('h384));

assign mul_ln1118_140_fu_779_p0 = tmp_data_V_6_reg_12193;

assign mul_ln1118_140_fu_779_p2 = ($signed(mul_ln1118_140_fu_779_p0) * $signed('h3C7));

assign mul_ln1118_141_fu_753_p0 = tmp_data_V_7_reg_12198;

assign mul_ln1118_141_fu_753_p2 = ($signed(mul_ln1118_141_fu_753_p0) * $signed('h365));

assign mul_ln1118_142_fu_667_p0 = tmp_data_V_8_reg_12203;

assign mul_ln1118_142_fu_667_p2 = ($signed(mul_ln1118_142_fu_667_p0) * $signed('h39F));

assign mul_ln1118_143_fu_722_p0 = tmp_data_V_9_reg_12208;

assign mul_ln1118_143_fu_722_p2 = ($signed(mul_ln1118_143_fu_722_p0) * $signed('h412));

assign mul_ln1118_144_fu_806_p0 = tmp_data_V_10_reg_12213;

assign mul_ln1118_144_fu_806_p2 = ($signed(mul_ln1118_144_fu_806_p0) * $signed('h45F));

assign mul_ln1118_145_fu_751_p0 = tmp_data_V_11_reg_12218;

assign mul_ln1118_145_fu_751_p2 = ($signed(mul_ln1118_145_fu_751_p0) * $signed('h3FA));

assign mul_ln1118_146_fu_823_p0 = tmp_data_V_12_reg_12223;

assign mul_ln1118_146_fu_823_p2 = ($signed(mul_ln1118_146_fu_823_p0) * $signed('h328));

assign mul_ln1118_147_fu_716_p0 = tmp_data_V_1322_reg_12228;

assign mul_ln1118_147_fu_716_p2 = ($signed(mul_ln1118_147_fu_716_p0) * $signed('h34C));

assign mul_ln1118_148_fu_664_p0 = tmp_data_V_14_reg_12233;

assign mul_ln1118_148_fu_664_p2 = ($signed(mul_ln1118_148_fu_664_p0) * $signed('h383));

assign mul_ln1118_149_fu_783_p0 = tmp_data_V_15_reg_12238;

assign mul_ln1118_149_fu_783_p2 = ($signed(mul_ln1118_149_fu_783_p0) * $signed('h405));

assign mul_ln1118_fu_728_p0 = tmp_data_V_0_reg_12163;

assign mul_ln1118_fu_728_p2 = ($signed(mul_ln1118_fu_728_p0) * $signed('h41E));

assign res_V_data_0_V_din = (trunc_ln_reg_12243 + 16'd188);

assign res_V_data_10_V_din = (trunc_ln708_132_reg_12293 + 16'd600);

assign res_V_data_11_V_din = (trunc_ln708_133_reg_12298 + 16'd484);

assign res_V_data_12_V_din = (trunc_ln708_134_reg_12303 + 16'd418);

assign res_V_data_13_V_din = (trunc_ln708_135_reg_12308 + 16'd913);

assign res_V_data_14_V_din = (trunc_ln708_136_reg_12313 + 16'd71);

assign res_V_data_15_V_din = (trunc_ln708_137_reg_12318 + 16'd678);

assign res_V_data_1_V_din = ($signed(trunc_ln708_s_reg_12248) + $signed(16'd65331));

assign res_V_data_2_V_din = (trunc_ln708_124_reg_12253 + 16'd261);

assign res_V_data_3_V_din = (trunc_ln708_125_reg_12258 + 16'd677);

assign res_V_data_4_V_din = (trunc_ln708_126_reg_12263 + 16'd398);

assign res_V_data_5_V_din = (trunc_ln708_127_reg_12268 + 16'd87);

assign res_V_data_6_V_din = (trunc_ln708_128_reg_12273 + 16'd583);

assign res_V_data_7_V_din = (trunc_ln708_129_reg_12278 + 16'd449);

assign res_V_data_8_V_din = (trunc_ln708_130_reg_12283 + 16'd1011);

assign res_V_data_9_V_din = (trunc_ln708_131_reg_12288 + 16'd707);

assign start_out = real_start;

endmodule //normalize_array_array_ap_fixed_16u_config9_s
