// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reduce_ap_fixed_4_Op_max_ap_fixed_16_6_0_0_0_s (
        ap_ready,
        x_0_V_read,
        x_1_V_read,
        x_2_V_read,
        x_3_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] x_0_V_read;
input  [15:0] x_1_V_read;
input  [15:0] x_2_V_read;
input  [15:0] x_3_V_read;
output  [15:0] ap_return;

wire   [0:0] icmp_ln1496_fu_34_p2;
wire   [0:0] icmp_ln1496_9_fu_48_p2;
wire   [15:0] select_ln86_fu_40_p3;
wire   [15:0] select_ln86_9_fu_54_p3;
wire   [0:0] icmp_ln1496_10_fu_62_p2;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln1496_10_fu_62_p2[0:0] === 1'b1) ? select_ln86_9_fu_54_p3 : select_ln86_fu_40_p3);

assign icmp_ln1496_10_fu_62_p2 = (($signed(select_ln86_fu_40_p3) < $signed(select_ln86_9_fu_54_p3)) ? 1'b1 : 1'b0);

assign icmp_ln1496_9_fu_48_p2 = (($signed(x_2_V_read) < $signed(x_3_V_read)) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_34_p2 = (($signed(x_0_V_read) < $signed(x_1_V_read)) ? 1'b1 : 1'b0);

assign select_ln86_9_fu_54_p3 = ((icmp_ln1496_9_fu_48_p2[0:0] === 1'b1) ? x_3_V_read : x_2_V_read);

assign select_ln86_fu_40_p3 = ((icmp_ln1496_fu_34_p2[0:0] === 1'b1) ? x_1_V_read : x_0_V_read);

endmodule //reduce_ap_fixed_4_Op_max_ap_fixed_16_6_0_0_0_s
