// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reduce_ap_fixed_4_Op_add_ap_fixed_18_8_0_0_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_V,
        x_1_V,
        x_2_V,
        x_3_V,
        x_4_V,
        x_5_V,
        x_6_V,
        x_7_V,
        x_8_V,
        x_9_V,
        x_V_offset,
        ap_return,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] x_0_V;
input  [16:0] x_1_V;
input  [16:0] x_2_V;
input  [16:0] x_3_V;
input  [16:0] x_4_V;
input  [16:0] x_5_V;
input  [16:0] x_6_V;
input  [16:0] x_7_V;
input  [16:0] x_8_V;
input  [16:0] x_9_V;
input  [4:0] x_V_offset;
output  [17:0] ap_return;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] p_Result_s_reg_550;
wire   [17:0] p_Val2_34_fu_246_p2;
reg   [17:0] p_Val2_34_reg_557;
reg   [0:0] p_Result_22_reg_563;
reg   [0:0] p_Result_23_reg_570;
wire   [17:0] p_Val2_37_fu_354_p2;
reg   [17:0] p_Val2_37_reg_577;
reg   [0:0] p_Result_24_reg_583;
wire   [17:0] zext_ln53_fu_122_p1;
wire   [17:0] zext_ln53_2_fu_126_p1;
wire   [17:0] zext_ln53_3_fu_130_p1;
wire   [17:0] zext_ln53_4_fu_134_p1;
wire   [17:0] zext_ln53_5_fu_138_p1;
wire   [17:0] zext_ln53_6_fu_142_p1;
wire   [17:0] zext_ln53_7_fu_146_p1;
wire   [17:0] zext_ln53_8_fu_150_p1;
wire   [17:0] zext_ln53_9_fu_154_p1;
wire   [17:0] zext_ln53_10_fu_158_p1;
wire   [3:0] p_Val2_s_fu_162_p11;
wire   [2:0] empty_fu_114_p1;
wire   [2:0] add_ln53_fu_188_p2;
wire   [3:0] p_Val2_32_fu_198_p11;
wire  signed [17:0] p_Val2_s_fu_162_p12;
wire  signed [17:0] p_Val2_32_fu_198_p12;
wire  signed [18:0] rhs_V_2_fu_228_p1;
wire  signed [18:0] lhs_V_2_fu_224_p1;
wire   [18:0] ret_V_fu_232_p2;
wire   [2:0] add_ln55_fu_260_p2;
wire   [3:0] p_Val2_35_fu_270_p11;
wire   [2:0] add_ln53_1_fu_296_p2;
wire   [3:0] p_Val2_2_fu_306_p11;
wire  signed [17:0] p_Val2_35_fu_270_p12;
wire  signed [17:0] p_Val2_2_fu_306_p12;
wire  signed [18:0] rhs_V_3_fu_336_p1;
wire  signed [18:0] lhs_V_3_fu_332_p1;
wire   [18:0] ret_V_2_fu_340_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] xor_ln786_12_fu_368_p2;
wire   [0:0] xor_ln340_25_fu_382_p2;
wire   [0:0] xor_ln340_24_fu_378_p2;
wire   [0:0] underflow_fu_373_p2;
wire   [0:0] or_ln340_12_fu_387_p2;
wire   [17:0] select_ln340_24_fu_392_p3;
wire   [17:0] select_ln388_12_fu_399_p3;
wire   [0:0] xor_ln786_13_fu_414_p2;
wire   [0:0] xor_ln340_27_fu_428_p2;
wire   [0:0] xor_ln340_26_fu_424_p2;
wire   [0:0] underflow_2_fu_419_p2;
wire   [0:0] or_ln340_13_fu_433_p2;
wire   [17:0] select_ln340_26_fu_438_p3;
wire   [17:0] select_ln388_13_fu_445_p3;
wire  signed [17:0] p_Val2_38_fu_406_p3;
wire  signed [17:0] p_Val2_39_fu_452_p3;
wire  signed [18:0] lhs_V_fu_460_p1;
wire  signed [18:0] rhs_V_fu_464_p1;
wire   [18:0] ret_V_3_fu_468_p2;
wire   [17:0] p_Val2_41_fu_482_p2;
wire   [0:0] p_Result_26_fu_488_p3;
wire   [0:0] p_Result_25_fu_474_p3;
wire   [0:0] xor_ln786_fu_496_p2;
wire   [0:0] xor_ln340_fu_514_p2;
wire   [0:0] xor_ln340_28_fu_508_p2;
wire   [0:0] underflow_3_fu_502_p2;
wire   [0:0] or_ln340_fu_520_p2;
wire   [17:0] select_ln340_fu_526_p3;
wire   [17:0] select_ln388_fu_534_p3;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

myproject_mux_104_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
myproject_mux_104_18_1_1_U3460(
    .din0(zext_ln53_fu_122_p1),
    .din1(zext_ln53_2_fu_126_p1),
    .din2(zext_ln53_3_fu_130_p1),
    .din3(zext_ln53_4_fu_134_p1),
    .din4(zext_ln53_5_fu_138_p1),
    .din5(zext_ln53_6_fu_142_p1),
    .din6(zext_ln53_7_fu_146_p1),
    .din7(zext_ln53_8_fu_150_p1),
    .din8(zext_ln53_9_fu_154_p1),
    .din9(zext_ln53_10_fu_158_p1),
    .din10(p_Val2_s_fu_162_p11),
    .dout(p_Val2_s_fu_162_p12)
);

myproject_mux_104_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
myproject_mux_104_18_1_1_U3461(
    .din0(zext_ln53_fu_122_p1),
    .din1(zext_ln53_2_fu_126_p1),
    .din2(zext_ln53_3_fu_130_p1),
    .din3(zext_ln53_4_fu_134_p1),
    .din4(zext_ln53_5_fu_138_p1),
    .din5(zext_ln53_6_fu_142_p1),
    .din6(zext_ln53_7_fu_146_p1),
    .din7(zext_ln53_8_fu_150_p1),
    .din8(zext_ln53_9_fu_154_p1),
    .din9(zext_ln53_10_fu_158_p1),
    .din10(p_Val2_32_fu_198_p11),
    .dout(p_Val2_32_fu_198_p12)
);

myproject_mux_104_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
myproject_mux_104_18_1_1_U3462(
    .din0(zext_ln53_fu_122_p1),
    .din1(zext_ln53_2_fu_126_p1),
    .din2(zext_ln53_3_fu_130_p1),
    .din3(zext_ln53_4_fu_134_p1),
    .din4(zext_ln53_5_fu_138_p1),
    .din5(zext_ln53_6_fu_142_p1),
    .din6(zext_ln53_7_fu_146_p1),
    .din7(zext_ln53_8_fu_150_p1),
    .din8(zext_ln53_9_fu_154_p1),
    .din9(zext_ln53_10_fu_158_p1),
    .din10(p_Val2_35_fu_270_p11),
    .dout(p_Val2_35_fu_270_p12)
);

myproject_mux_104_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 18 ),
    .din3_WIDTH( 18 ),
    .din4_WIDTH( 18 ),
    .din5_WIDTH( 18 ),
    .din6_WIDTH( 18 ),
    .din7_WIDTH( 18 ),
    .din8_WIDTH( 18 ),
    .din9_WIDTH( 18 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 18 ))
myproject_mux_104_18_1_1_U3463(
    .din0(zext_ln53_fu_122_p1),
    .din1(zext_ln53_2_fu_126_p1),
    .din2(zext_ln53_3_fu_130_p1),
    .din3(zext_ln53_4_fu_134_p1),
    .din4(zext_ln53_5_fu_138_p1),
    .din5(zext_ln53_6_fu_142_p1),
    .din6(zext_ln53_7_fu_146_p1),
    .din7(zext_ln53_8_fu_150_p1),
    .din8(zext_ln53_9_fu_154_p1),
    .din9(zext_ln53_10_fu_158_p1),
    .din10(p_Val2_2_fu_306_p11),
    .dout(p_Val2_2_fu_306_p12)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Result_22_reg_563 <= p_Val2_34_fu_246_p2[32'd17];
        p_Result_23_reg_570 <= ret_V_2_fu_340_p2[32'd18];
        p_Result_24_reg_583 <= p_Val2_37_fu_354_p2[32'd17];
        p_Result_s_reg_550 <= ret_V_fu_232_p2[32'd18];
        p_Val2_34_reg_557 <= p_Val2_34_fu_246_p2;
        p_Val2_37_reg_577 <= p_Val2_37_fu_354_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_1_fu_296_p2 = (3'd3 + empty_fu_114_p1);

assign add_ln53_fu_188_p2 = (3'd1 + empty_fu_114_p1);

assign add_ln55_fu_260_p2 = (3'd2 + empty_fu_114_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = ((or_ln340_fu_520_p2[0:0] === 1'b1) ? select_ln340_fu_526_p3 : select_ln388_fu_534_p3);

assign empty_fu_114_p1 = x_V_offset[2:0];

assign lhs_V_2_fu_224_p1 = p_Val2_s_fu_162_p12;

assign lhs_V_3_fu_332_p1 = p_Val2_35_fu_270_p12;

assign lhs_V_fu_460_p1 = p_Val2_38_fu_406_p3;

assign or_ln340_12_fu_387_p2 = (xor_ln340_25_fu_382_p2 | p_Result_22_reg_563);

assign or_ln340_13_fu_433_p2 = (xor_ln340_27_fu_428_p2 | p_Result_24_reg_583);

assign or_ln340_fu_520_p2 = (xor_ln340_fu_514_p2 | p_Result_26_fu_488_p3);

assign p_Result_25_fu_474_p3 = ret_V_3_fu_468_p2[32'd18];

assign p_Result_26_fu_488_p3 = p_Val2_41_fu_482_p2[32'd17];

assign p_Val2_2_fu_306_p11 = add_ln53_1_fu_296_p2;

assign p_Val2_32_fu_198_p11 = add_ln53_fu_188_p2;

assign p_Val2_34_fu_246_p2 = ($signed(p_Val2_s_fu_162_p12) + $signed(p_Val2_32_fu_198_p12));

assign p_Val2_35_fu_270_p11 = add_ln55_fu_260_p2;

assign p_Val2_37_fu_354_p2 = ($signed(p_Val2_35_fu_270_p12) + $signed(p_Val2_2_fu_306_p12));

assign p_Val2_38_fu_406_p3 = ((or_ln340_12_fu_387_p2[0:0] === 1'b1) ? select_ln340_24_fu_392_p3 : select_ln388_12_fu_399_p3);

assign p_Val2_39_fu_452_p3 = ((or_ln340_13_fu_433_p2[0:0] === 1'b1) ? select_ln340_26_fu_438_p3 : select_ln388_13_fu_445_p3);

assign p_Val2_41_fu_482_p2 = ($signed(p_Val2_39_fu_452_p3) + $signed(p_Val2_38_fu_406_p3));

assign p_Val2_s_fu_162_p11 = x_V_offset[3:0];

assign ret_V_2_fu_340_p2 = ($signed(rhs_V_3_fu_336_p1) + $signed(lhs_V_3_fu_332_p1));

assign ret_V_3_fu_468_p2 = ($signed(lhs_V_fu_460_p1) + $signed(rhs_V_fu_464_p1));

assign ret_V_fu_232_p2 = ($signed(rhs_V_2_fu_228_p1) + $signed(lhs_V_2_fu_224_p1));

assign rhs_V_2_fu_228_p1 = p_Val2_32_fu_198_p12;

assign rhs_V_3_fu_336_p1 = p_Val2_2_fu_306_p12;

assign rhs_V_fu_464_p1 = p_Val2_39_fu_452_p3;

assign select_ln340_24_fu_392_p3 = ((xor_ln340_24_fu_378_p2[0:0] === 1'b1) ? 18'd131071 : p_Val2_34_reg_557);

assign select_ln340_26_fu_438_p3 = ((xor_ln340_26_fu_424_p2[0:0] === 1'b1) ? 18'd131071 : p_Val2_37_reg_577);

assign select_ln340_fu_526_p3 = ((xor_ln340_28_fu_508_p2[0:0] === 1'b1) ? 18'd131071 : p_Val2_41_fu_482_p2);

assign select_ln388_12_fu_399_p3 = ((underflow_fu_373_p2[0:0] === 1'b1) ? 18'd131072 : p_Val2_34_reg_557);

assign select_ln388_13_fu_445_p3 = ((underflow_2_fu_419_p2[0:0] === 1'b1) ? 18'd131072 : p_Val2_37_reg_577);

assign select_ln388_fu_534_p3 = ((underflow_3_fu_502_p2[0:0] === 1'b1) ? 18'd131072 : p_Val2_41_fu_482_p2);

assign underflow_2_fu_419_p2 = (xor_ln786_13_fu_414_p2 & p_Result_23_reg_570);

assign underflow_3_fu_502_p2 = (xor_ln786_fu_496_p2 & p_Result_25_fu_474_p3);

assign underflow_fu_373_p2 = (xor_ln786_12_fu_368_p2 & p_Result_s_reg_550);

assign xor_ln340_24_fu_378_p2 = (p_Result_s_reg_550 ^ p_Result_22_reg_563);

assign xor_ln340_25_fu_382_p2 = (p_Result_s_reg_550 ^ 1'd1);

assign xor_ln340_26_fu_424_p2 = (p_Result_24_reg_583 ^ p_Result_23_reg_570);

assign xor_ln340_27_fu_428_p2 = (p_Result_23_reg_570 ^ 1'd1);

assign xor_ln340_28_fu_508_p2 = (p_Result_26_fu_488_p3 ^ p_Result_25_fu_474_p3);

assign xor_ln340_fu_514_p2 = (p_Result_25_fu_474_p3 ^ 1'd1);

assign xor_ln786_12_fu_368_p2 = (p_Result_22_reg_563 ^ 1'd1);

assign xor_ln786_13_fu_414_p2 = (p_Result_24_reg_583 ^ 1'd1);

assign xor_ln786_fu_496_p2 = (p_Result_26_fu_488_p3 ^ 1'd1);

assign zext_ln53_10_fu_158_p1 = x_9_V;

assign zext_ln53_2_fu_126_p1 = x_1_V;

assign zext_ln53_3_fu_130_p1 = x_2_V;

assign zext_ln53_4_fu_134_p1 = x_3_V;

assign zext_ln53_5_fu_138_p1 = x_4_V;

assign zext_ln53_6_fu_142_p1 = x_5_V;

assign zext_ln53_7_fu_146_p1 = x_6_V;

assign zext_ln53_8_fu_150_p1 = x_7_V;

assign zext_ln53_9_fu_154_p1 = x_8_V;

assign zext_ln53_fu_122_p1 = x_0_V;

endmodule //reduce_ap_fixed_4_Op_add_ap_fixed_18_8_0_0_0_s
