// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module softmax_array_array_ap_fixed_10u_softmax_config28_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        data_V_data_4_V_dout,
        data_V_data_4_V_empty_n,
        data_V_data_4_V_read,
        data_V_data_5_V_dout,
        data_V_data_5_V_empty_n,
        data_V_data_5_V_read,
        data_V_data_6_V_dout,
        data_V_data_6_V_empty_n,
        data_V_data_6_V_read,
        data_V_data_7_V_dout,
        data_V_data_7_V_empty_n,
        data_V_data_7_V_read,
        data_V_data_8_V_dout,
        data_V_data_8_V_empty_n,
        data_V_data_8_V_read,
        data_V_data_9_V_dout,
        data_V_data_9_V_empty_n,
        data_V_data_9_V_read,
        res_V_data_0_V_TDATA,
        res_V_data_0_V_TVALID,
        res_V_data_0_V_TREADY,
        res_V_data_1_V_TDATA,
        res_V_data_1_V_TVALID,
        res_V_data_1_V_TREADY,
        res_V_data_2_V_TDATA,
        res_V_data_2_V_TVALID,
        res_V_data_2_V_TREADY,
        res_V_data_3_V_TDATA,
        res_V_data_3_V_TVALID,
        res_V_data_3_V_TREADY,
        res_V_data_4_V_TDATA,
        res_V_data_4_V_TVALID,
        res_V_data_4_V_TREADY,
        res_V_data_5_V_TDATA,
        res_V_data_5_V_TVALID,
        res_V_data_5_V_TREADY,
        res_V_data_6_V_TDATA,
        res_V_data_6_V_TVALID,
        res_V_data_6_V_TREADY,
        res_V_data_7_V_TDATA,
        res_V_data_7_V_TVALID,
        res_V_data_7_V_TREADY,
        res_V_data_8_V_TDATA,
        res_V_data_8_V_TVALID,
        res_V_data_8_V_TREADY,
        res_V_data_9_V_TDATA,
        res_V_data_9_V_TVALID,
        res_V_data_9_V_TREADY
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [15:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [15:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [15:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
input  [15:0] data_V_data_4_V_dout;
input   data_V_data_4_V_empty_n;
output   data_V_data_4_V_read;
input  [15:0] data_V_data_5_V_dout;
input   data_V_data_5_V_empty_n;
output   data_V_data_5_V_read;
input  [15:0] data_V_data_6_V_dout;
input   data_V_data_6_V_empty_n;
output   data_V_data_6_V_read;
input  [15:0] data_V_data_7_V_dout;
input   data_V_data_7_V_empty_n;
output   data_V_data_7_V_read;
input  [15:0] data_V_data_8_V_dout;
input   data_V_data_8_V_empty_n;
output   data_V_data_8_V_read;
input  [15:0] data_V_data_9_V_dout;
input   data_V_data_9_V_empty_n;
output   data_V_data_9_V_read;
output  [15:0] res_V_data_0_V_TDATA;
output   res_V_data_0_V_TVALID;
input   res_V_data_0_V_TREADY;
output  [15:0] res_V_data_1_V_TDATA;
output   res_V_data_1_V_TVALID;
input   res_V_data_1_V_TREADY;
output  [15:0] res_V_data_2_V_TDATA;
output   res_V_data_2_V_TVALID;
input   res_V_data_2_V_TREADY;
output  [15:0] res_V_data_3_V_TDATA;
output   res_V_data_3_V_TVALID;
input   res_V_data_3_V_TREADY;
output  [15:0] res_V_data_4_V_TDATA;
output   res_V_data_4_V_TVALID;
input   res_V_data_4_V_TREADY;
output  [15:0] res_V_data_5_V_TDATA;
output   res_V_data_5_V_TVALID;
input   res_V_data_5_V_TREADY;
output  [15:0] res_V_data_6_V_TDATA;
output   res_V_data_6_V_TVALID;
input   res_V_data_6_V_TREADY;
output  [15:0] res_V_data_7_V_TDATA;
output   res_V_data_7_V_TVALID;
input   res_V_data_7_V_TREADY;
output  [15:0] res_V_data_8_V_TDATA;
output   res_V_data_8_V_TVALID;
input   res_V_data_8_V_TREADY;
output  [15:0] res_V_data_9_V_TDATA;
output   res_V_data_9_V_TVALID;
input   res_V_data_9_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg data_V_data_4_V_read;
reg data_V_data_5_V_read;
reg data_V_data_6_V_read;
reg data_V_data_7_V_read;
reg data_V_data_8_V_read;
reg data_V_data_9_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_state31;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n;
reg    data_V_data_1_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n;
reg    data_V_data_2_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n;
reg    data_V_data_3_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n;
reg    data_V_data_4_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n;
reg    data_V_data_5_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n;
reg    data_V_data_6_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n;
reg    data_V_data_7_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n;
reg    data_V_data_8_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n;
reg    data_V_data_9_V_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n;
reg    res_V_data_0_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n;
reg    res_V_data_1_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n;
reg    res_V_data_2_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n;
reg    res_V_data_3_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n;
reg    res_V_data_4_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n;
reg    res_V_data_5_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n;
reg    res_V_data_6_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n;
reg    res_V_data_7_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n;
reg    res_V_data_8_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n;
reg    res_V_data_9_V_TDATA_blk_n;
reg    grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_start;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_done;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_idle;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_ready;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_read;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_read;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TVALID;
wire    grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TREADY;
reg    ap_block_state1_ignore_call20;
wire    ap_CS_fsm_state32;
wire    regslice_both_res_V_data_0_V_U_apdone_blk;
wire    regslice_both_res_V_data_1_V_U_apdone_blk;
wire    regslice_both_res_V_data_2_V_U_apdone_blk;
wire    regslice_both_res_V_data_3_V_U_apdone_blk;
wire    regslice_both_res_V_data_4_V_U_apdone_blk;
wire    regslice_both_res_V_data_5_V_U_apdone_blk;
wire    regslice_both_res_V_data_6_V_U_apdone_blk;
wire    regslice_both_res_V_data_7_V_U_apdone_blk;
wire    regslice_both_res_V_data_8_V_U_apdone_blk;
wire    regslice_both_res_V_data_9_V_U_apdone_blk;
reg    ap_block_state32;
reg   [31:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_block_state31;
wire    res_V_data_0_V_TREADY_int;
wire    regslice_both_res_V_data_0_V_U_vld_out;
wire    res_V_data_1_V_TREADY_int;
wire    regslice_both_res_V_data_1_V_U_vld_out;
wire    res_V_data_2_V_TREADY_int;
wire    regslice_both_res_V_data_2_V_U_vld_out;
wire    res_V_data_3_V_TREADY_int;
wire    regslice_both_res_V_data_3_V_U_vld_out;
wire    res_V_data_4_V_TREADY_int;
wire    regslice_both_res_V_data_4_V_U_vld_out;
wire    res_V_data_5_V_TREADY_int;
wire    regslice_both_res_V_data_5_V_U_vld_out;
wire    res_V_data_6_V_TREADY_int;
wire    regslice_both_res_V_data_6_V_U_vld_out;
wire    res_V_data_7_V_TREADY_int;
wire    regslice_both_res_V_data_7_V_U_vld_out;
wire    res_V_data_8_V_TREADY_int;
wire    regslice_both_res_V_data_8_V_U_vld_out;
wire    res_V_data_9_V_TREADY_int;
wire    regslice_both_res_V_data_9_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 32'd1;
end

softmax_stable_array_array_softmax_config28_s grp_softmax_stable_array_array_softmax_config28_s_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_start),
    .ap_done(grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_done),
    .ap_idle(grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_idle),
    .ap_ready(grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_ready),
    .data_V_data_0_V_dout(data_V_data_0_V_dout),
    .data_V_data_0_V_empty_n(data_V_data_0_V_empty_n),
    .data_V_data_0_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_read),
    .data_V_data_1_V_dout(data_V_data_1_V_dout),
    .data_V_data_1_V_empty_n(data_V_data_1_V_empty_n),
    .data_V_data_1_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_read),
    .data_V_data_2_V_dout(data_V_data_2_V_dout),
    .data_V_data_2_V_empty_n(data_V_data_2_V_empty_n),
    .data_V_data_2_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_read),
    .data_V_data_3_V_dout(data_V_data_3_V_dout),
    .data_V_data_3_V_empty_n(data_V_data_3_V_empty_n),
    .data_V_data_3_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_read),
    .data_V_data_4_V_dout(data_V_data_4_V_dout),
    .data_V_data_4_V_empty_n(data_V_data_4_V_empty_n),
    .data_V_data_4_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_read),
    .data_V_data_5_V_dout(data_V_data_5_V_dout),
    .data_V_data_5_V_empty_n(data_V_data_5_V_empty_n),
    .data_V_data_5_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_read),
    .data_V_data_6_V_dout(data_V_data_6_V_dout),
    .data_V_data_6_V_empty_n(data_V_data_6_V_empty_n),
    .data_V_data_6_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_read),
    .data_V_data_7_V_dout(data_V_data_7_V_dout),
    .data_V_data_7_V_empty_n(data_V_data_7_V_empty_n),
    .data_V_data_7_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_read),
    .data_V_data_8_V_dout(data_V_data_8_V_dout),
    .data_V_data_8_V_empty_n(data_V_data_8_V_empty_n),
    .data_V_data_8_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_read),
    .data_V_data_9_V_dout(data_V_data_9_V_dout),
    .data_V_data_9_V_empty_n(data_V_data_9_V_empty_n),
    .data_V_data_9_V_read(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_read),
    .res_V_data_0_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA),
    .res_V_data_0_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TVALID),
    .res_V_data_0_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TREADY),
    .res_V_data_1_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA),
    .res_V_data_1_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TVALID),
    .res_V_data_1_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TREADY),
    .res_V_data_2_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA),
    .res_V_data_2_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TVALID),
    .res_V_data_2_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TREADY),
    .res_V_data_3_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA),
    .res_V_data_3_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TVALID),
    .res_V_data_3_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TREADY),
    .res_V_data_4_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA),
    .res_V_data_4_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TVALID),
    .res_V_data_4_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TREADY),
    .res_V_data_5_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA),
    .res_V_data_5_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TVALID),
    .res_V_data_5_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TREADY),
    .res_V_data_6_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA),
    .res_V_data_6_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TVALID),
    .res_V_data_6_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TREADY),
    .res_V_data_7_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA),
    .res_V_data_7_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TVALID),
    .res_V_data_7_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TREADY),
    .res_V_data_8_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA),
    .res_V_data_8_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TVALID),
    .res_V_data_8_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TREADY),
    .res_V_data_9_V_TDATA(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA),
    .res_V_data_9_V_TVALID(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TVALID),
    .res_V_data_9_V_TREADY(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TREADY),
    .data_V_data_0_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n),
    .data_V_data_1_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n),
    .data_V_data_2_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n),
    .data_V_data_3_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n),
    .data_V_data_4_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n),
    .data_V_data_5_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n),
    .data_V_data_6_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n),
    .data_V_data_7_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n),
    .data_V_data_8_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n),
    .data_V_data_9_V_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n),
    .res_V_data_0_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n),
    .res_V_data_1_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n),
    .res_V_data_2_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n),
    .res_V_data_3_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n),
    .res_V_data_4_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n),
    .res_V_data_5_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n),
    .res_V_data_6_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n),
    .res_V_data_7_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n),
    .res_V_data_8_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n),
    .res_V_data_9_V_TDATA_blk_n(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TVALID),
    .ack_in(res_V_data_0_V_TREADY_int),
    .data_out(res_V_data_0_V_TDATA),
    .vld_out(regslice_both_res_V_data_0_V_U_vld_out),
    .ack_out(res_V_data_0_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_0_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_1_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TVALID),
    .ack_in(res_V_data_1_V_TREADY_int),
    .data_out(res_V_data_1_V_TDATA),
    .vld_out(regslice_both_res_V_data_1_V_U_vld_out),
    .ack_out(res_V_data_1_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_1_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_2_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TVALID),
    .ack_in(res_V_data_2_V_TREADY_int),
    .data_out(res_V_data_2_V_TDATA),
    .vld_out(regslice_both_res_V_data_2_V_U_vld_out),
    .ack_out(res_V_data_2_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_2_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_3_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TVALID),
    .ack_in(res_V_data_3_V_TREADY_int),
    .data_out(res_V_data_3_V_TDATA),
    .vld_out(regslice_both_res_V_data_3_V_U_vld_out),
    .ack_out(res_V_data_3_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_3_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_4_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TVALID),
    .ack_in(res_V_data_4_V_TREADY_int),
    .data_out(res_V_data_4_V_TDATA),
    .vld_out(regslice_both_res_V_data_4_V_U_vld_out),
    .ack_out(res_V_data_4_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_4_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_5_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TVALID),
    .ack_in(res_V_data_5_V_TREADY_int),
    .data_out(res_V_data_5_V_TDATA),
    .vld_out(regslice_both_res_V_data_5_V_U_vld_out),
    .ack_out(res_V_data_5_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_5_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_6_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TVALID),
    .ack_in(res_V_data_6_V_TREADY_int),
    .data_out(res_V_data_6_V_TDATA),
    .vld_out(regslice_both_res_V_data_6_V_U_vld_out),
    .ack_out(res_V_data_6_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_6_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_7_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TVALID),
    .ack_in(res_V_data_7_V_TREADY_int),
    .data_out(res_V_data_7_V_TDATA),
    .vld_out(regslice_both_res_V_data_7_V_U_vld_out),
    .ack_out(res_V_data_7_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_7_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_8_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TVALID),
    .ack_in(res_V_data_8_V_TREADY_int),
    .data_out(res_V_data_8_V_TDATA),
    .vld_out(regslice_both_res_V_data_8_V_U_vld_out),
    .ack_out(res_V_data_8_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_8_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 16 ))
regslice_both_res_V_data_9_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA),
    .vld_in(grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TVALID),
    .ack_in(res_V_data_9_V_TREADY_int),
    .data_out(res_V_data_9_V_TDATA),
    .vld_out(regslice_both_res_V_data_9_V_U_vld_out),
    .ack_out(res_V_data_9_V_TREADY),
    .apdone_blk(regslice_both_res_V_data_9_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((regslice_both_res_V_data_9_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_8_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_7_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_6_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_5_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_4_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_3_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_2_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_1_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_0_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state32))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((~((regslice_both_res_V_data_9_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_8_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_7_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_6_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_5_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_4_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_3_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_2_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_1_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_0_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state32))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_res_V_data_9_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_8_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_7_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_6_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_5_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_4_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_3_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_2_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_1_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_0_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state32))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_0_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_0_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_read;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_1_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_1_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_read;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_2_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_2_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_read;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_3_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_3_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_read;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_4_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n;
    end else begin
        data_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_4_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_read;
    end else begin
        data_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_5_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n;
    end else begin
        data_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_5_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_read;
    end else begin
        data_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_6_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n;
    end else begin
        data_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_6_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_read;
    end else begin
        data_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_7_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n;
    end else begin
        data_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_7_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_read;
    end else begin
        data_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_8_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n;
    end else begin
        data_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_8_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_read;
    end else begin
        data_V_data_8_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_9_V_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n;
    end else begin
        data_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_9_V_read = grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_read;
    end else begin
        data_V_data_9_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_start = 1'b1;
    end else begin
        grp_softmax_stable_array_array_softmax_config28_s_fu_184_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_0_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n;
    end else begin
        res_V_data_0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_1_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n;
    end else begin
        res_V_data_1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_2_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n;
    end else begin
        res_V_data_2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_3_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n;
    end else begin
        res_V_data_3_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_4_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n;
    end else begin
        res_V_data_4_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_5_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n;
    end else begin
        res_V_data_5_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_6_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n;
    end else begin
        res_V_data_6_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_7_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n;
    end else begin
        res_V_data_7_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_8_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n;
    end else begin
        res_V_data_8_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_9_V_TDATA_blk_n = grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n;
    end else begin
        res_V_data_9_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if ((~((grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n == 1'b0)) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            if ((~((regslice_both_res_V_data_9_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_8_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_7_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_6_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_5_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_4_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_3_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_2_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_1_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_0_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call20 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state31 = ((grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_9_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_8_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_7_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_6_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_5_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_4_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_softmax_config28_s_fu_184_data_V_data_0_V_blk_n == 1'b0));
end

always @ (*) begin
    ap_block_state32 = ((regslice_both_res_V_data_9_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_8_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_7_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_6_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_5_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_4_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_3_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_2_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_1_V_U_apdone_blk == 1'b1) | (regslice_both_res_V_data_0_V_U_apdone_blk == 1'b1));
end

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_0_V_TREADY = (res_V_data_0_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_1_V_TREADY = (res_V_data_1_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_2_V_TREADY = (res_V_data_2_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_3_V_TREADY = (res_V_data_3_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_4_V_TREADY = (res_V_data_4_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_5_V_TREADY = (res_V_data_5_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_6_V_TREADY = (res_V_data_6_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_7_V_TREADY = (res_V_data_7_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_8_V_TREADY = (res_V_data_8_V_TREADY_int & ap_CS_fsm_state31);

assign grp_softmax_stable_array_array_softmax_config28_s_fu_184_res_V_data_9_V_TREADY = (res_V_data_9_V_TREADY_int & ap_CS_fsm_state31);

assign res_V_data_0_V_TVALID = regslice_both_res_V_data_0_V_U_vld_out;

assign res_V_data_1_V_TVALID = regslice_both_res_V_data_1_V_U_vld_out;

assign res_V_data_2_V_TVALID = regslice_both_res_V_data_2_V_U_vld_out;

assign res_V_data_3_V_TVALID = regslice_both_res_V_data_3_V_U_vld_out;

assign res_V_data_4_V_TVALID = regslice_both_res_V_data_4_V_U_vld_out;

assign res_V_data_5_V_TVALID = regslice_both_res_V_data_5_V_U_vld_out;

assign res_V_data_6_V_TVALID = regslice_both_res_V_data_6_V_U_vld_out;

assign res_V_data_7_V_TVALID = regslice_both_res_V_data_7_V_U_vld_out;

assign res_V_data_8_V_TVALID = regslice_both_res_V_data_8_V_U_vld_out;

assign res_V_data_9_V_TVALID = regslice_both_res_V_data_9_V_U_vld_out;

endmodule //softmax_array_array_ap_fixed_10u_softmax_config28_s
